plugins {
    id 'com.gradleup.shadow'
}

architectury {
    platformSetupLoomIde()
    fabric()
}

repositories {
    maven { url = "https://maven.terraformersmc.com/" }
}

configurations {
    common {
        canBeResolved = true
        canBeConsumed = false
    }
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentFabric.extendsFrom common

    shadowBundle {
        canBeResolved = true
        canBeConsumed = false
    }
    apiElements {
        outgoing.artifacts.clear()
        outgoing.artifact(remapJar)
    }
    runtimeElements {
        outgoing.artifacts.clear()
        outgoing.artifact(remapJar)
    }
}

dependencies {
    modImplementation "net.fabricmc:fabric-language-kotlin:$rootProject.fabric_kotlin_version"
    modImplementation "net.fabricmc:fabric-loader:$rootProject.fabric_loader_version"
    modImplementation "net.fabricmc.fabric-api:fabric-api:$rootProject.fabric_api_version"
    modCompileOnly "com.terraformersmc:modmenu:$rootProject.modmenu_version"

    common(project(path: ':common', configuration: 'namedElements')) { transitive false }
    shadowBundle project(path: ':common', configuration: 'transformProductionFabric')
    implementation("com.github.usefulness:webp-imageio:$rootProject.fabric_webp_version") { transitive = false }
    shadowBundle("com.github.usefulness:webp-imageio:$rootProject.fabric_webp_version") { transitive = false }
}

processResources {
    inputs.property 'version', project.version
    inputs.property 'fabric_kotlin_version', rootProject.fabric_kotlin_version

    filesMatching('fabric.mod.json') {
        expand version: project.version, fabric_kotlin_version: rootProject.fabric_kotlin_version
    }
}

jar {
    archiveClassifier = "raw"
}

shadowJar {
    dependsOn(jar)
    mainSpec.sourcePaths.clear()
    from(jar)
    configurations = [project.configurations.shadowBundle]
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    archiveClassifier = "dev-shadow"
    from(rootDir.toPath().toString() + "/LICENSE") {
        rename { "${it}_${rootProject.archives_name}"}
    }
}

remapJar {
    inputFile.set(shadowJar.archiveFile)
    dependsOn shadowJar
    archiveClassifier = null
}
