plugins {
    id 'com.gradleup.shadow'
}

architectury {
    platformSetupLoomIde()
    forge()
}

configurations {
    common {
        canBeResolved = true
        canBeConsumed = false
    }
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentForge.extendsFrom common

    shadowBundle {
        canBeResolved = true
        canBeConsumed = false
    }
    apiElements {
        outgoing.artifacts.clear()
        outgoing.artifact(remapJar)
    }
    runtimeElements {
        outgoing.artifacts.clear()
        outgoing.artifact(remapJar)
    }
}

repositories {
    maven {
        name = 'MinecraftForge'
        url = 'https://maven.minecraftforge.net/'
    }
}

dependencies {
    forge "net.minecraftforge:forge:$rootProject.forge_version"

    common(project(path: ':common', configuration: 'namedElements')) { transitive false }
    shadowBundle project(path: ':common', configuration: 'transformProductionForge')
    shadowBundle "com.github.usefulness:webp-imageio:0.11.0"
    forgeRuntimeLibrary "com.github.usefulness:webp-imageio:0.11.0"
}

processResources {
    inputs.property 'version', project.version

    filesMatching('META-INF/mods.toml') {
        expand version: project.version
    }
}

jar {
    manifest.attributes 'MixinConfigs': 'respawnrecap.mixins.json'
    archiveClassifier = "raw"
}

shadowJar {
    exclude 'org/jetbrains/annotations/**'
    exclude 'org/intellij/lang/annotations/**'
    dependsOn(jar)
    mainSpec.sourcePaths.clear()
    from(jar)
    configurations = [project.configurations.shadowBundle]
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    archiveClassifier = "dev-shadow"
    from(rootDir.toPath().toString() + "/LICENSE") {
        rename { "${it}_${rootProject.archives_name}"}
    }
}

remapJar {
    atAccessWideners.add('respawnrecap.accesswidener')
    inputFile.set(shadowJar.archiveFile)
    dependsOn shadowJar
    archiveClassifier = null
}
