plugins {
    id 'com.gradleup.shadow'
}

architectury {
    platformSetupLoomIde()
    forge()
}

configurations {
    common {
        canBeResolved = true
        canBeConsumed = false
    }
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentForge.extendsFrom common

    shadowBundle {
        canBeResolved = true
        canBeConsumed = false
    }
    apiElements {
        outgoing.artifacts.clear()
        outgoing.artifact(remapJar)
    }
    runtimeElements {
        outgoing.artifacts.clear()
        outgoing.artifact(remapJar)
    }
}

repositories {
    maven { url = 'https://thedarkcolour.github.io/KotlinForForge/' }
    maven {
        name = 'MinecraftForge'
        url = 'https://maven.minecraftforge.net/'
    }
}

dependencies {
    forge "net.minecraftforge:forge:$rootProject.forge_version"
    implementation "thedarkcolour:kotlinforforge:$rootProject.kotlin_for_forge_version"

    common(project(path: ':common', configuration: 'namedElements')) { transitive false }
    shadowBundle project(path: ':common', configuration: 'transformProductionForge')
    implementation("com.github.usefulness:webp-imageio:$rootProject.forge_webp_version") { transitive = false }
    shadowBundle("com.github.usefulness:webp-imageio:$rootProject.forge_webp_version") { transitive = false }
}

loom {
    mods {
        respawnrecap {
            sourceSet sourceSets.main
            // Keep WebP in the mod layer so it can access KotlinForForge in development.
            dependency(project.dependencies.create("com.github.usefulness:webp-imageio:$rootProject.forge_webp_version") {
                transitive = false
            })
        }
    }
}

processResources {
    inputs.property 'version', project.version
    inputs.property 'kotlin_for_forge_version', rootProject.kotlin_for_forge_version

    filesMatching('META-INF/mods.toml') {
        expand version: project.version, kotlin_for_forge_version: rootProject.kotlin_for_forge_version
    }
}

jar {
    manifest.attributes 'MixinConfigs': 'respawnrecap.mixins.json'
    archiveClassifier = "raw"
}

shadowJar {
    exclude 'org/jetbrains/annotations/**'
    exclude 'org/intellij/lang/annotations/**'
    dependsOn(jar)
    mainSpec.sourcePaths.clear()
    from(jar)
    configurations = [project.configurations.shadowBundle]
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    archiveClassifier = "dev-shadow"
    from(rootDir.toPath().toString() + "/LICENSE") {
        rename { "${it}_${rootProject.archives_name}"}
    }
}

remapJar {
    atAccessWideners.add('respawnrecap.accesswidener')
    inputFile.set(shadowJar.archiveFile)
    dependsOn shadowJar
    archiveClassifier = null
}
