modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"
issueTrackerURL = "https://github.com/DialingSpoon527/Respawn-Recap/issues"

[[mods]]
modId = "respawnrecap"
version = "${version}"
displayName = "Respawn Recap"
displayURL = "https://github.com/DialingSpoon527/Respawn-Recap"
logoFile = "icon.png"
authors = "DialingSpoon"
description = '''
outer wilds inspired respawn animation
'''

[[dependencies.respawnrecap]]
modId = "neoforge"
type = "required"
versionRange = "(21.1, 21.5)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.respawnrecap]]
modId = "minecraft"
type = "required"
versionRange = "(1.21.1, 1.21.5)"
ordering = "NONE"
side = "CLIENT"

[[mixins]]
config = "respawnrecap.mixins.json"
